name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  fake_it: 
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
