name: fake_it
description: best faker library for dart
version: 0.0.1
homepage: https://github.com/easazade/fake_it

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
  # equatable: ^2.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  glob: ^2.1.1
  recase: ^4.1.0
  mustache_template: ^2.0.0
  collection: ^1.17.1
