name: fake_it
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
  # equatable: ^2.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
