name: faker_x
description: BEST faker package available for dart. One that the Dart community deserves.
version: 0.4.13
homepage: https://github.com/easazade/faker_x

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  pointycastle: ^3.7.0  


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  glob: ^2.1.1
  recase: ^4.1.0
  mustache_template: ^2.0.0
  collection: ^1.17.1
  yaml: ^3.1.1