name: faker_x
description: BEST faker package available for dart. One that the Dart community deserves.
version: 0.6.16
homepage: https://github.com/easazade/faker_x

environment:
  sdk: ">=2.14.3 <4.0.0"

dependencies:
  pointycastle: ^3.7.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  glob: ^2.1.2
  recase: ^4.1.0
  mustache_template: ^2.0.0
  collection: ^1.18.0
  yaml: ^3.1.2
