import 'package:fake_it/src/base/data_list.dart';
import 'package:fake_it/src/base/format.dart';

const jobPrefixes = DataList(
  values: [
    'Lead',
    'Senior',
    'Direct',
    'Corporate',
    'Dynamic',
    'Future',
    'Product',
    'National',
    'Regional',
    'District',
    'Central',
    'Global',
    'Customer',
    'Investor',
    'Dynamic',
    'International',
    'Legacy',
    'Forward',
    'Internal',
    'Human',
    'Chief',
    'Principal',
  ],
);

const jobSufixes = DataList(
  values: [
    'Supervisor',
    'Associate',
    'Executive',
    'Liason',
    'Officer',
    'Manager',
    'Engineer',
    'Specialist',
    'Director',
    'Coordinator',
    'Administrator',
    'Architect',
    'Analyst',
    'Designer',
    'Planner',
    'Orchestrator',
    'Technician',
    'Developer',
    'Producer',
    'Consultant',
    'Assistant',
    'Facilitator',
    'Agent',
    'Representative',
    'Strategist',
  ],
);

const jobTitles = DataList(
  formats: [
    Format('{{jobPrefixes}} {{jobTitles}} {{jobSufixes}}'),
    Format('{{jobPrefixes}} {{jobTitles}}'),
    Format('{{jobTitles}} {{jobSufixes}}'),
  ],
  values: [
    //TODO: these job titles should be changed.
    'Supervisor',
    'Associate',
    'Executive',
    'Liason',
    'Officer',
    'Manager',
    'Engineer',
    'Specialist',
    'Director',
    'Coordinator',
    'Administrator',
    'Architect',
    'Analyst',
    'Designer',
    'Planner',
    'Orchestrator',
    'Technician',
    'Developer',
    'Producer',
    'Consultant',
    'Assistant',
    'Facilitator',
    'Agent',
    'Representative',
    'Strategist',
  ],
);
