name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        sdk: [ stable ]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib/ test/

      - name: Analyze project source
        run: dart analyze

      - name: Generate library code and tests
        run: 
          - dart script/regenerate_base_classes.dart
          - dart script/generate_all.dart
          - dart script/create_tests.dart

      - name: Run tests
        run: dart test